/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    // 👇 So Tailwind picks up classes inside rendered markdown and any MDX
    "./content/**/*.{md,mdx}",
  ],
  theme: {
    extend: {
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            maxWidth: "65ch",
            color: theme("colors.slate.800"),
            h1: { color: theme("colors.slate.900"), fontWeight: "700", letterSpacing: "-0.02em" },
            h2: { color: theme("colors.slate.900"), fontWeight: "700", letterSpacing: "-0.02em" },
            h3: { color: theme("colors.slate.900"), fontWeight: "600" },
            a: {
              color: theme("colors.slate.900"),
              textDecoration: "underline",
              textUnderlineOffset: "4px",
              transition: "color .2s",
              "&:hover": { color: theme("colors.slate.700") },
            },
            strong: { color: theme("colors.slate.900") },
            blockquote: {
              fontStyle: "normal",
              borderLeftColor: theme("colors.slate.300"),
              color: theme("colors.slate.700"),
            },
            code: {
              backgroundColor: theme("colors.slate.100"),
              padding: "0.15rem 0.35rem",
              borderRadius: theme("borderRadius.lg"),
            },
            pre: {
              backgroundColor: theme("colors.slate.900"),
              color: theme("colors.slate.100"),
              borderRadius: theme("borderRadius.xl"),
              padding: "1rem 1.25rem",
            },
            img: { borderRadius: theme("borderRadius.xl") },
            hr: { borderColor: theme("colors.slate.200") },
          },
        },
        invert: {
          css: {
            color: theme("colors.slate.200"),
            h1: { color: theme("colors.white") },
            h2: { color: theme("colors.white") },
            h3: { color: theme("colors.slate.100") },
            a: { color: theme("colors.slate.100"), "&:hover": { color: theme("colors.white") } },
            strong: { color: theme("colors.white") },
            blockquote: { borderLeftColor: theme("colors.slate.600"), color: theme("colors.slate.300") },
            code: { backgroundColor: theme("colors.slate.800") },
            hr: { borderColor: theme("colors.slate.700") },
          },
        },
      }),
    },
  },
  // Small safelist so key utilities render even if scanning misfires
  safelist: [
    "bg-indigo-600",
    "hover:bg-indigo-700",
    "text-indigo-600",
    "dark:text-indigo-400",
    "bg-white",
    "bg-neutral-100",
    "hover:bg-neutral-100",
    "hover:bg-neutral-200",
    "dark:bg-neutral-950",
    "text-neutral-900",
    "text-neutral-700",
    "text-neutral-600",
    "text-neutral-500",
    "dark:text-neutral-100",
    "dark:text-neutral-400",
    "border-neutral-200",
    "dark:border-neutral-800",
    "rounded-sm",
    "shadow-sm",
    "hover:shadow-md",
    "hover:shadow-lg",
    "grid",
    "grid-cols-1",
    "md:grid-cols-3",
    "flex",
    "items-center",
    "justify-between",
  ],
  plugins: [require("@tailwindcss/typography")],
};